In [92]:
import numpy as np
import random
from numpy.linalg import norm

In [63]:
data = [2,43,11,56,74,23,88,1,94]

In [64]:
mean = np.mean(data)

In [65]:
mean

43.55555555555556

In [66]:
standard_deviation = np.std(data)

In [67]:
standard_deviation

34.354721852756235

In [68]:
matrix = np.random.randint(1,100,size=(5,5))

In [69]:
matrix

array([[50, 64,  3, 14, 30],
       [93, 59, 66,  7, 16],
       [87, 24, 83, 64,  1],
       [19, 70, 81, 50, 78],
       [52, 46, 10, 12, 17]])

In [70]:
np.max(matrix)

93

In [71]:
np.min(matrix)

1

In [72]:
max_col = np.max(matrix, axis=0)

In [73]:
min_col = np.min(matrix, axis=0)

In [74]:
max_col

array([93, 70, 83, 64, 78])

In [75]:
min_col

array([19, 24,  3,  7,  1])

In [80]:
max_rows = np.max(matrix[0]),np.max(matrix[1]),np.max(matrix[2]),np.max(matrix[3]),np.max(matrix[4])

In [81]:
min_rows = np.min(matrix[0]),np.min(matrix[1]),np.min(matrix[2]),np.min(matrix[3]),np.min(matrix[4])

In [82]:
max_rows

(64, 93, 87, 81, 52)

In [83]:
min_rows

(3, 7, 1, 19, 10)

In [93]:
a = np.array([2,4,6,8,10])
b = np.array([12,14,16,18,20])

In [95]:
cosine_similarity=np.dot(a,b) / (norm(a)*norm(b))

In [97]:
a,b,cosine_similarity

(array([ 2,  4,  6,  8, 10]), array([12, 14, 16, 18, 20]), 0.9649505047327671)